authsysproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_view

urlpatterns = [
    path('', views.index, name='home'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
     path('upload', views.index, name='index'),
    path('list', views.show, name='show'),
    # path('edit/<int:id>', views.edit),  
    # path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy),
    path('login/', auth_view.LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', auth_view.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
]

users/models.py
from django.db import models  
class VideoLib(models.Model):  
    mobile = models.CharField(max_length=100)  
    name = models.EmailField()  
    file = models.FileField()
    file_b  = models.CharField(max_length=100, null=True)  
    user = models.IntegerField(default=0, null=True)
    status = models.CharField(max_length=10, null=True)  
    file_status = models.CharField(max_length=10, null=True)  
    file_b_status = models.CharField(max_length=10, null=True)  
    file_upload_time = models.DateTimeField(auto_now_add=True, null=True)
    file_b_upload_time = models.DateTimeField(auto_now_add=True, null=True)

    class Meta:  
        db_table = "video_lib"

users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from users.models import VideoLib  
from django import forms


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class CreateForm(forms.Form):  
    name = forms.CharField(label="Enter  name",max_length=50)  
    mobile  = forms.CharField(label="Enter mobile", max_length = 10)  
    file = forms.FileField(label="Chose Video File")
   

class EmployeeForm(forms.ModelForm):  
    class Meta:  
        model = VideoLib  
        fields = "__all__"            

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import UserRegisterForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from moviepy.editor import *
import json

from users.functions import handle_uploaded_file  
from users.functions import merge_videos  
from users.forms import CreateForm  
from users.models import VideoLib



def home(request):
    return render(request, 'users/home.html')

def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Hi {username}, your account was created successfully')
            return redirect('home')
    else:
        form = UserRegisterForm()

    return render(request, 'users/register.html', {'form': form})
@login_required()
def index(request):  
    # /form_data = json.loads(request.data)
    # exit()
    if request.method == 'POST':  
        vid_lib = VideoLib()
        vid_lib.name = request.POST.get('name')
        vid_lib.mobile = request.POST.get('mobile')
        
        saved_path = handle_uploaded_file(request.FILES['file'])  

        print(saved_path)
        #vid_lib.file = saved_path
        
        vid_lib.save()
        # merge_videos()
        return redirect("/list")          
            
    else:  
        video = CreateForm()  
        return render(request,"users/index.html",{'form':video})
@login_required()
def show(request):  
    videos = VideoLib.objects.all()  
    return render(request,"users/show.html",{'videos':videos})    

def destroy(request, id):  
    video = VideoLib.objects.get(id=id)  
    video.delete()  
    return redirect("/list")        



@login_required()
def profile(request):
    return render(request, 'users/profile.html')

    

users/templates/users/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--Css Style -->
    <link rel="stylesheet" href="{% static 'users/css/main.css' %}" type="text/css">

    <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
    crossorigin="anonymous"
  />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
    crossorigin="anonymous"
  ></script>
<!--Font Link-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&family=Open+Sans:wght@800&display=swap" rel="stylesheet">

    <style type="text/css">

      #gum,#recorded{
        width:400px
      }
      </style>
  </head>
  <body class="bg-light">
  {% load static %}
      
    <div class="container py-3">
          <header>
            <div
              class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom"
            >
              <a
                href="/"
                class="d-flex align-items-center text-dark text-decoration-none"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="40"
                  height="32"
                  class="me-2"
                  viewBox="0 0 118 94"
                  role="img"
                >
                  <title>Bootstrap</title>
                  <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"
                    fill="currentColor"
                  ></path>
                </svg>
                <span class="fs-4">Video Library</span>
              </a>
    
              <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
               
                {% if user.is_authenticated %}
                <a href="{% url 'show' %}" class="btn" > List </a>
                <a href="{% url 'profile' %}" class="btn" > Profile </a>
                <a href="{% url 'logout' %}" class="btn" > Logout </a>
              {% else %}
                <a href="{% url 'register' %}" class="btn" > Create Account </a>
                <a href="{% url 'login' %}" class="btn" >Log In</a>
              {% endif %}
              </nav>
            </div>
          </header>
          <main>
          {% if messages %}
          {% for message in messages %}
            <div class="alert alert-{{message.tags}}">{{message}}</div>
          {% endfor %}
        {% endif %}
        
        {% block content %}
        {% endblock content %}
      
    </main>
    </div>

      <!-- Optional JavaScript; choose one of the two! -->

      <!-- Option 1: Bootstrap Bundle with Popper -->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

      <!-- Option 2: Separate Popper and Bootstrap JS -->
      <!--
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
      -->
      <script src="{% static 'users/js/main.js' %}" async></script>

  </body>
</html>

users/templates/users/home.html
{% extends 'users/base.html' %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <div class="container">
            <div class="row g-0">
                <div class="col-sm-6 col-md-8" id="header-text">
                  <h1 id="header-h1">Multi-regulated <br> global broker. </h1>
                  <p id="header-paragraph">A trusted destination for traders worldwide, <br> Authorised by FCA, ASIC & FSCA</p>
                  <a class="btn" style="color: white; background-color: #fd5e14;"type="submit" id="body-link-row">Discover More</a>
                </div>

                <div class="col-6 col-md-4" id="header-image"><img src="images/in-liquid-slide-2.svg " alt=""></div>
              </div>
    </div>


{% endblock content %}

users/templates/users/index.html
{% extends 'users/base.html' %} {% load crispy_forms_tags %} {% block content %}
<!--
<form method="POST" class="form" enctype="multipart/form-data" id="v-register">
  {% csrf_token %} {{ form.as_table }}
  <button type="submit" class="save btn btn-primary">Save Record</button>
</form>
-->
<form id ="video-form">
  <legend> Please Record your message</legend>
  <div class="row g-5">
    <div class="col-md-7 col-lg-8">
      <div class="bd-example g-3">
        <div class="mb-3">
          <label for="exampleFormControlInput1" class="form-label"
            >Name</label
          >
          <input
            type="text"
            class="form-control"
            id="id_name"
            placeholder="name"
          />
        </div>
        <div class="mb-3">
          <label for="exampleFormControlTextarea1" class="form-label"
            >Mobile</label
          >
          <input
            type="text"
            class="form-control"
            id="id_mobile"
            placeholder="mobile"
          />
        </div>
      </div>
    </div>
  </div>
  
</form>

<div id="container">
  <label for="exampleFormControlTextarea1" class="form-label"
          >Mobile</label
        >
  <div>
    <button id="start" class="btn btn-primary">Start camera</button>
    <button id="record" class="btn btn-default" disabled>Start Recording</button>
    <button id="play" class="btn btn-default" disabled>Play</button>
    <button id="magic" class="btn btn-primary" disabled>Submit </button>
    <!--<button id="download" disabled>Download</button>  -->
  </div>

  <video id="gum" playsinline autoplay muted></video>
  <video id="recorded" playsinline loop></video>


  <div style="display: none">
    Recording format:
    <select id="codecPreferences" disabled></select>
  </div>
  <div style="display: none">
    <h4>Media Stream Constraints options</h4>
    <p>
      Echo cancellation:
      <input type="checkbox" id="echoCancellation" />
    </p>
  </div>

  <div>
    <span id="errorMsg"></span>
  </div>
</div>

<script type="text/javascript">
  function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== "") {
      const cookies = document.cookie.split(";");
      for (let i = 0; i < cookies.length; i++) {
        const cookie = cookies[i].trim();
        // Does this cookie string begin with the name we want?
        if (cookie.substring(0, name.length + 1) === name + "=") {
          cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
          break;
        }
      }
    }
    return cookieValue;
  }
  // JavaScript wrapper function to send HTTP requests using Django's "X-CSRFToken" request header
  function sendHttpAsync(path, method, body) {
    let props = {
      method: method,
      headers: {
        "X-CSRFToken": getCookie("csrftoken"),
      },
      mode: "same-origin",
    };

    if (body !== null && body !== undefined) {
      props.body = JSON.stringify(body);
    }

    return fetch(path, props)
      .then((response) => {
        return response.json().then((result) => {
          return {
            ok: response.ok,
            body: result,
          };
        });
      })
      .then((resultObj) => {
        return resultObj;
      })
      .catch((error) => {
        throw error;
      });
  }
  window.onload = function () {

    $("event").on('submit',function(e){

    })
    const playButton = document.querySelector("button#magic");
    playButton.addEventListener("click", () => {
      const formData = new FormData();
      const formData1 = document.querySelector("#v-register");

      formData.append("name", $( "#id_name" ).val());
      formData.append("mobile",$( "#id_mobile" ).val()); // number 123456 is immediately converted to a string "123456"

      // HTML file input, chosen by user
      //formData.append("userfile", fileInputElement.files[0]);

      // JavaScript file-like object
      const content = '<q id="a"><span id="b">hey!</span></q>'; // the body of the new file…
      const blob = new Blob(recordedBlobs, { type: "video/webm" });
      formData.append("file", blob);

      const request = new XMLHttpRequest();

      request.open("POST", "http://127.0.0.1:8000/");
      let csrfToken = getCookie("csrftoken");

      request.setRequestHeader("X-CSRFToken", csrfToken);
      request.send(formData);
      alert('submited')
      $("#gum").hide();
    });
  };
</script>
{% endblock %}

users/templates/users/login.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    {% comment %} <link rel="stylesheet" href="{% static 'css/main.css' %}"> {% endcomment %}
    <div class="container" style="margin-top: 30px;">
    <form action="" method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
          <legend class="border-bottom mb-4" style="color: white;">Sign In Now</legend>
          {{ form|crispy }}
      </fieldset>
      <div class="form-group" >
          <button class="btn btn-primary">Sign In</button>
      </div>
      <div class="form-group">
          <small class="text-muted ml-3" >Don't have an account yet? <a href="{% url 'register' %}">Sign Up Today</a></small>
      </div>
    </form>
    </div>
{% endblock %}</title>

users/templates/users/logout.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <div class="container">
        <h1>You have been Logged out</h1>
        <h5><a href="{% url 'login' %}">Login In Again</a></h5>
    </div>
{% endblock %}</title>

users/templates/users/profile.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <div class="container">
        <h2>{{user.username}}</h2>
    <h2>{{user.email}}</h2>
    </div>

    <div id="container">

        <h1><a href="//webrtc.github.io/samples/" title="WebRTC samples homepage">WebRTC samples</a>
            <span>MediaRecorder</span></h1>
    
        <p>For more information see the MediaStream Recording API <a
                href="http://w3c.github.io/mediacapture-record/MediaRecorder.html"
                title="W3C MediaStream Recording API Editor's Draft">Editor's&nbsp;Draft</a>.</p>
    
        <video id="gum" playsinline autoplay muted></video>
        <video id="recorded" playsinline loop></video>
    
        <div>
            <button id="start">Start camera</button>
            <button id="record" disabled>Start Recording</button>
            <button id="play" disabled>Play</button>
            <button id="download" disabled>Download</button>
        </div>
    
        <div>
            Recording format: <select id="codecPreferences" disabled></select>
        </div>
        <div>
            <h4>Media Stream Constraints options</h4>
            <p>Echo cancellation: <input type="checkbox" id="echoCancellation"></p>
        </div>
    
        <div>
            <span id="errorMsg"></span>
        </div>
    
    
    </div>
    
{% endblock %}

users/templates/users/register.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <div class="container" style="margin-top: 30px;">
    <form action="" method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
          <legend class="border-bottom mb-4" style="color: white;">Join Now</legend>
          {{ form|crispy }}
      </fieldset>
      <div class="form-group" >
          <button class="btn btn-primary">Sign Up</button>
      </div>
      <div class="form-group">
          <small class="text-muted ml-3" >Already have an account? <a href="{% url 'login' %}">Sign In</a></small>
      </div>
    </form>
    </div>
{% endblock %}

users/templates/users/show.html
{% extends 'users/base.html' %}

{% block content %} 
<div style="width: 100%">
    <a href="{% url 'index' %}" class="btn btn-primary " style="float: right">Add </a>
  
</div>
    
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        <th> ID</th>  
        <th> Name</th>  
        <th>Mobile</th>  
        <th>File</th>  
        <th>Actions</th>  
    </tr>  
    </thead>  
    <tbody>  
{% for video in videos %}  
    <tr>  
        <td>{{ video.id }}</td>  
        <td>{{ video.name }}</td>  
        <td>{{ video.mobile }}</td>  
        <td>{{ video.file }}</td>  
        <td>  
            <a href="/edit/{{ video.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="/delete/{{ video.id }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  

      
{% endblock %}